version: "3.8"
services:
  db:
    image: postgres:14
    container_name: genai_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Krushna@5605
      POSTGRES_DB: genai_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
